//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.WillServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WillServiceReference.IWillWcfService")]
    public interface IWillWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWillWcfService/GetWillMessage", ReplyAction="http://tempuri.org/IWillWcfService/GetWillMessageResponse")]
        string GetWillMessage(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWillWcfService/GetWillMessage", ReplyAction="http://tempuri.org/IWillWcfService/GetWillMessageResponse")]
        System.Threading.Tasks.Task<string> GetWillMessageAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWillWcfServiceChannel : ConsoleClient.WillServiceReference.IWillWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WillWcfServiceClient : System.ServiceModel.ClientBase<ConsoleClient.WillServiceReference.IWillWcfService>, ConsoleClient.WillServiceReference.IWillWcfService {
        
        public WillWcfServiceClient() {
        }
        
        public WillWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WillWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WillWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WillWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWillMessage(int value) {
            return base.Channel.GetWillMessage(value);
        }
        
        public System.Threading.Tasks.Task<string> GetWillMessageAsync(int value) {
            return base.Channel.GetWillMessageAsync(value);
        }
    }
}
