//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.JudyWcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JudyWcfServiceReference.IJudyWcfService")]
    public interface IJudyWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJudyWcfService/GetJudyMessage", ReplyAction="http://tempuri.org/IJudyWcfService/GetJudyMessageResponse")]
        string GetJudyMessage(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJudyWcfService/GetJudyMessage", ReplyAction="http://tempuri.org/IJudyWcfService/GetJudyMessageResponse")]
        System.Threading.Tasks.Task<string> GetJudyMessageAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJudyWcfServiceChannel : ConsoleClient.JudyWcfServiceReference.IJudyWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JudyWcfServiceClient : System.ServiceModel.ClientBase<ConsoleClient.JudyWcfServiceReference.IJudyWcfService>, ConsoleClient.JudyWcfServiceReference.IJudyWcfService {
        
        public JudyWcfServiceClient() {
        }
        
        public JudyWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JudyWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JudyWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JudyWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetJudyMessage(int value) {
            return base.Channel.GetJudyMessage(value);
        }
        
        public System.Threading.Tasks.Task<string> GetJudyMessageAsync(int value) {
            return base.Channel.GetJudyMessageAsync(value);
        }
    }
}
